# Generated by Django 2.2.23 on 2021-05-13 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=30)),
                ('amount', models.PositiveIntegerField()),
                ('o_id', models.CharField(max_length=30, null=True)),
                ('amount_paid', models.PositiveIntegerField(null=True)),
                ('amount_due', models.PositiveIntegerField(null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('offer_id', models.IntegerField(default=None, null=True)),
                ('status', models.CharField(default='initiated', max_length=15)),
                ('attempts', models.PositiveIntegerField(null=True)),
                ('notes', models.TextField(null=True)),
                ('created_at', models.PositiveIntegerField(null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payments', models.ManyToManyField(to='payments.Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=30)),
                ('amount', models.PositiveIntegerField()),
                ('notes', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('payments', models.ManyToManyField(to='payments.Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
